### ISSUE TITLE
Not a bug. Communication request.

### ISSUE THREAD

**Issue by youcancallmemaster** [araten10/EdgewarePlusPlus#74]
Howdy. The only platform you've given outside of Github is Twitter, which I don't have an appropriate account for.
I'm looking to build a similar-ish program to EdgeWare, and would like help and/or insight. I intend for it to be a techdom program of sorts.
Email me at chargedruby@proton.me or DM on discord "youcancallmemaster" if you'd please.

**Comment by araten10** [comment]
hello- I am not sure how much advice I can give but if you wish to send me something feel free to send it to araten10 on discord. I don't use discord much at all since I don't like the program personally, but if you don't have twitter it's probably the best way to contact me. If I don't respond for a while i'm not ghosting you- I just infrequently check it
